[all]
workspace = true
avoid_cfg_tarpaulin = true
all-features = true
exclude = []
exclude-files = [
  "examples/**/*",
  "poem-derive/**/*",
  "poem-openapi-derive/**/*",
  "poem-grpc-build/**/*",
]
